/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSharedPresetRouteImport } from './routes/_authenticated/shared-preset'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOutletsRouteImport } from './routes/_authenticated/outlets'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLiveMonitorRouteImport } from './routes/_authenticated/live-monitor'
import { Route as AuthenticatedFilterPresetsRouteImport } from './routes/_authenticated/filter-presets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedCommandCentreRouteImport } from './routes/_authenticated/command-centre'
import { Route as AuthenticatedCamerasRouteImport } from './routes/_authenticated/cameras'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAlertCentreRouteImport } from './routes/_authenticated/alert-centre'
import { Route as AuthenticatedAlertAnalyticsRouteImport } from './routes/_authenticated/alert-analytics'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedConversationiqIndexRouteImport } from './routes/_authenticated/conversationiq.index'
import { Route as AuthenticatedAdministrationIndexRouteImport } from './routes/_authenticated/administration.index'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as AuthenticatedInfrastructureStorageRouteImport } from './routes/_authenticated/infrastructure.storage'
import { Route as AuthenticatedInfrastructureNetworkRouteImport } from './routes/_authenticated/infrastructure.network'
import { Route as AuthenticatedInfrastructureHealthRouteImport } from './routes/_authenticated/infrastructure.health'
import { Route as AuthenticatedInfrastructureGatewaysRouteImport } from './routes/_authenticated/infrastructure.gateways'
import { Route as AuthenticatedInfrastructureEnginesRouteImport } from './routes/_authenticated/infrastructure.engines'
import { Route as AuthenticatedInfrastructureCamerasRouteImport } from './routes/_authenticated/infrastructure.cameras'
import { Route as AuthenticatedInfrastructureAudioRouteImport } from './routes/_authenticated/infrastructure.audio'
import { Route as AuthenticatedCopilotReportsRouteImport } from './routes/_authenticated/copilot.reports'
import { Route as AuthenticatedCopilotReportTemplatesRouteImport } from './routes/_authenticated/copilot.report-templates'
import { Route as AuthenticatedCopilotNotificationsRouteImport } from './routes/_authenticated/copilot.notifications'
import { Route as AuthenticatedConversationiqSlaRouteImport } from './routes/_authenticated/conversationiq.sla'
import { Route as AuthenticatedConversationiqSearchRouteImport } from './routes/_authenticated/conversationiq.search'
import { Route as AuthenticatedConversationiqReviewRouteImport } from './routes/_authenticated/conversationiq.review'
import { Route as AuthenticatedConversationiqRedactionsRouteImport } from './routes/_authenticated/conversationiq.redactions'
import { Route as AuthenticatedConversationiqQueueRouteImport } from './routes/_authenticated/conversationiq.queue'
import { Route as AuthenticatedConversationiqLanguagesRouteImport } from './routes/_authenticated/conversationiq.languages'
import { Route as AuthenticatedConversationiqKeywordsRouteImport } from './routes/_authenticated/conversationiq.keywords'
import { Route as AuthenticatedConversationiqAuditRouteImport } from './routes/_authenticated/conversationiq.audit'
import { Route as AuthenticatedConversationiqConversationIdRouteImport } from './routes/_authenticated/conversationiq.$conversationId'
import { Route as AuthenticatedAdministrationUsageRouteImport } from './routes/_authenticated/administration.usage'
import { Route as AuthenticatedAdministrationSpeechRouteImport } from './routes/_authenticated/administration.speech'
import { Route as AuthenticatedAdministrationSecurityRouteImport } from './routes/_authenticated/administration.security'
import { Route as AuthenticatedAdministrationQuotasRouteImport } from './routes/_authenticated/administration.quotas'
import { Route as AuthenticatedAdministrationLicensingRouteImport } from './routes/_authenticated/administration.licensing'
import { Route as AuthenticatedAdministrationLanguagesRouteImport } from './routes/_authenticated/administration.languages'
import { Route as AuthenticatedAdministrationKeywordsRouteImport } from './routes/_authenticated/administration.keywords'
import { Route as AuthenticatedAdministrationIntegrationsRouteImport } from './routes/_authenticated/administration.integrations'
import { Route as AuthenticatedAdministrationGeneralRouteImport } from './routes/_authenticated/administration.general'
import { Route as AuthenticatedAdministrationBackupRouteImport } from './routes/_authenticated/administration.backup'
import { Route as AuthenticatedAdministrationApiKeysRouteImport } from './routes/_authenticated/administration.api-keys'
import { Route as AuthenticatedAdministrationAlertsRouteImport } from './routes/_authenticated/administration.alerts'
import { Route as AuthenticatedAdministrationAiRouteImport } from './routes/_authenticated/administration.ai'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminCopilotAuditRouteImport } from './routes/_authenticated/admin.copilot-audit'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharedPresetRoute =
  AuthenticatedSharedPresetRouteImport.update({
    id: '/shared-preset',
    path: '/shared-preset',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutletsRoute = AuthenticatedOutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveMonitorRoute =
  AuthenticatedLiveMonitorRouteImport.update({
    id: '/live-monitor',
    path: '/live-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilterPresetsRoute =
  AuthenticatedFilterPresetsRouteImport.update({
    id: '/filter-presets',
    path: '/filter-presets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandCentreRoute =
  AuthenticatedCommandCentreRouteImport.update({
    id: '/command-centre',
    path: '/command-centre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCamerasRoute = AuthenticatedCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertCentreRoute =
  AuthenticatedAlertCentreRouteImport.update({
    id: '/alert-centre',
    path: '/alert-centre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertAnalyticsRoute =
  AuthenticatedAlertAnalyticsRouteImport.update({
    id: '/alert-analytics',
    path: '/alert-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqIndexRoute =
  AuthenticatedConversationiqIndexRouteImport.update({
    id: '/conversationiq/',
    path: '/conversationiq/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrationIndexRoute =
  AuthenticatedAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInfrastructureStorageRoute =
  AuthenticatedInfrastructureStorageRouteImport.update({
    id: '/infrastructure/storage',
    path: '/infrastructure/storage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureNetworkRoute =
  AuthenticatedInfrastructureNetworkRouteImport.update({
    id: '/infrastructure/network',
    path: '/infrastructure/network',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureHealthRoute =
  AuthenticatedInfrastructureHealthRouteImport.update({
    id: '/infrastructure/health',
    path: '/infrastructure/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureGatewaysRoute =
  AuthenticatedInfrastructureGatewaysRouteImport.update({
    id: '/infrastructure/gateways',
    path: '/infrastructure/gateways',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureEnginesRoute =
  AuthenticatedInfrastructureEnginesRouteImport.update({
    id: '/infrastructure/engines',
    path: '/infrastructure/engines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureCamerasRoute =
  AuthenticatedInfrastructureCamerasRouteImport.update({
    id: '/infrastructure/cameras',
    path: '/infrastructure/cameras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructureAudioRoute =
  AuthenticatedInfrastructureAudioRouteImport.update({
    id: '/infrastructure/audio',
    path: '/infrastructure/audio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotReportsRoute =
  AuthenticatedCopilotReportsRouteImport.update({
    id: '/copilot/reports',
    path: '/copilot/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotReportTemplatesRoute =
  AuthenticatedCopilotReportTemplatesRouteImport.update({
    id: '/copilot/report-templates',
    path: '/copilot/report-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotNotificationsRoute =
  AuthenticatedCopilotNotificationsRouteImport.update({
    id: '/copilot/notifications',
    path: '/copilot/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqSlaRoute =
  AuthenticatedConversationiqSlaRouteImport.update({
    id: '/conversationiq/sla',
    path: '/conversationiq/sla',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqSearchRoute =
  AuthenticatedConversationiqSearchRouteImport.update({
    id: '/conversationiq/search',
    path: '/conversationiq/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqReviewRoute =
  AuthenticatedConversationiqReviewRouteImport.update({
    id: '/conversationiq/review',
    path: '/conversationiq/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqRedactionsRoute =
  AuthenticatedConversationiqRedactionsRouteImport.update({
    id: '/conversationiq/redactions',
    path: '/conversationiq/redactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqQueueRoute =
  AuthenticatedConversationiqQueueRouteImport.update({
    id: '/conversationiq/queue',
    path: '/conversationiq/queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqLanguagesRoute =
  AuthenticatedConversationiqLanguagesRouteImport.update({
    id: '/conversationiq/languages',
    path: '/conversationiq/languages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqKeywordsRoute =
  AuthenticatedConversationiqKeywordsRouteImport.update({
    id: '/conversationiq/keywords',
    path: '/conversationiq/keywords',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqAuditRoute =
  AuthenticatedConversationiqAuditRouteImport.update({
    id: '/conversationiq/audit',
    path: '/conversationiq/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationiqConversationIdRoute =
  AuthenticatedConversationiqConversationIdRouteImport.update({
    id: '/conversationiq/$conversationId',
    path: '/conversationiq/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrationUsageRoute =
  AuthenticatedAdministrationUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationSpeechRoute =
  AuthenticatedAdministrationSpeechRouteImport.update({
    id: '/speech',
    path: '/speech',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationSecurityRoute =
  AuthenticatedAdministrationSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationQuotasRoute =
  AuthenticatedAdministrationQuotasRouteImport.update({
    id: '/quotas',
    path: '/quotas',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationLicensingRoute =
  AuthenticatedAdministrationLicensingRouteImport.update({
    id: '/licensing',
    path: '/licensing',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationLanguagesRoute =
  AuthenticatedAdministrationLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationKeywordsRoute =
  AuthenticatedAdministrationKeywordsRouteImport.update({
    id: '/keywords',
    path: '/keywords',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationIntegrationsRoute =
  AuthenticatedAdministrationIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationGeneralRoute =
  AuthenticatedAdministrationGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationBackupRoute =
  AuthenticatedAdministrationBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationApiKeysRoute =
  AuthenticatedAdministrationApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationAlertsRoute =
  AuthenticatedAdministrationAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdministrationAiRoute =
  AuthenticatedAdministrationAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCopilotAuditRoute =
  AuthenticatedAdminCopilotAuditRouteImport.update({
    id: '/admin/copilot-audit',
    path: '/admin/copilot-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/alert-analytics': typeof AuthenticatedAlertAnalyticsRoute
  '/alert-centre': typeof AuthenticatedAlertCentreRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filter-presets': typeof AuthenticatedFilterPresetsRoute
  '/live-monitor': typeof AuthenticatedLiveMonitorRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/outlets': typeof AuthenticatedOutletsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shared-preset': typeof AuthenticatedSharedPresetRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/copilot-audit': typeof AuthenticatedAdminCopilotAuditRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/administration/ai': typeof AuthenticatedAdministrationAiRoute
  '/administration/alerts': typeof AuthenticatedAdministrationAlertsRoute
  '/administration/api-keys': typeof AuthenticatedAdministrationApiKeysRoute
  '/administration/backup': typeof AuthenticatedAdministrationBackupRoute
  '/administration/general': typeof AuthenticatedAdministrationGeneralRoute
  '/administration/integrations': typeof AuthenticatedAdministrationIntegrationsRoute
  '/administration/keywords': typeof AuthenticatedAdministrationKeywordsRoute
  '/administration/languages': typeof AuthenticatedAdministrationLanguagesRoute
  '/administration/licensing': typeof AuthenticatedAdministrationLicensingRoute
  '/administration/quotas': typeof AuthenticatedAdministrationQuotasRoute
  '/administration/security': typeof AuthenticatedAdministrationSecurityRoute
  '/administration/speech': typeof AuthenticatedAdministrationSpeechRoute
  '/administration/usage': typeof AuthenticatedAdministrationUsageRoute
  '/conversationiq/$conversationId': typeof AuthenticatedConversationiqConversationIdRoute
  '/conversationiq/audit': typeof AuthenticatedConversationiqAuditRoute
  '/conversationiq/keywords': typeof AuthenticatedConversationiqKeywordsRoute
  '/conversationiq/languages': typeof AuthenticatedConversationiqLanguagesRoute
  '/conversationiq/queue': typeof AuthenticatedConversationiqQueueRoute
  '/conversationiq/redactions': typeof AuthenticatedConversationiqRedactionsRoute
  '/conversationiq/review': typeof AuthenticatedConversationiqReviewRoute
  '/conversationiq/search': typeof AuthenticatedConversationiqSearchRoute
  '/conversationiq/sla': typeof AuthenticatedConversationiqSlaRoute
  '/copilot/notifications': typeof AuthenticatedCopilotNotificationsRoute
  '/copilot/report-templates': typeof AuthenticatedCopilotReportTemplatesRoute
  '/copilot/reports': typeof AuthenticatedCopilotReportsRoute
  '/infrastructure/audio': typeof AuthenticatedInfrastructureAudioRoute
  '/infrastructure/cameras': typeof AuthenticatedInfrastructureCamerasRoute
  '/infrastructure/engines': typeof AuthenticatedInfrastructureEnginesRoute
  '/infrastructure/gateways': typeof AuthenticatedInfrastructureGatewaysRoute
  '/infrastructure/health': typeof AuthenticatedInfrastructureHealthRoute
  '/infrastructure/network': typeof AuthenticatedInfrastructureNetworkRoute
  '/infrastructure/storage': typeof AuthenticatedInfrastructureStorageRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/conversationiq/': typeof AuthenticatedConversationiqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/alert-analytics': typeof AuthenticatedAlertAnalyticsRoute
  '/alert-centre': typeof AuthenticatedAlertCentreRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filter-presets': typeof AuthenticatedFilterPresetsRoute
  '/live-monitor': typeof AuthenticatedLiveMonitorRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/outlets': typeof AuthenticatedOutletsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shared-preset': typeof AuthenticatedSharedPresetRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/copilot-audit': typeof AuthenticatedAdminCopilotAuditRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/administration/ai': typeof AuthenticatedAdministrationAiRoute
  '/administration/alerts': typeof AuthenticatedAdministrationAlertsRoute
  '/administration/api-keys': typeof AuthenticatedAdministrationApiKeysRoute
  '/administration/backup': typeof AuthenticatedAdministrationBackupRoute
  '/administration/general': typeof AuthenticatedAdministrationGeneralRoute
  '/administration/integrations': typeof AuthenticatedAdministrationIntegrationsRoute
  '/administration/keywords': typeof AuthenticatedAdministrationKeywordsRoute
  '/administration/languages': typeof AuthenticatedAdministrationLanguagesRoute
  '/administration/licensing': typeof AuthenticatedAdministrationLicensingRoute
  '/administration/quotas': typeof AuthenticatedAdministrationQuotasRoute
  '/administration/security': typeof AuthenticatedAdministrationSecurityRoute
  '/administration/speech': typeof AuthenticatedAdministrationSpeechRoute
  '/administration/usage': typeof AuthenticatedAdministrationUsageRoute
  '/conversationiq/$conversationId': typeof AuthenticatedConversationiqConversationIdRoute
  '/conversationiq/audit': typeof AuthenticatedConversationiqAuditRoute
  '/conversationiq/keywords': typeof AuthenticatedConversationiqKeywordsRoute
  '/conversationiq/languages': typeof AuthenticatedConversationiqLanguagesRoute
  '/conversationiq/queue': typeof AuthenticatedConversationiqQueueRoute
  '/conversationiq/redactions': typeof AuthenticatedConversationiqRedactionsRoute
  '/conversationiq/review': typeof AuthenticatedConversationiqReviewRoute
  '/conversationiq/search': typeof AuthenticatedConversationiqSearchRoute
  '/conversationiq/sla': typeof AuthenticatedConversationiqSlaRoute
  '/copilot/notifications': typeof AuthenticatedCopilotNotificationsRoute
  '/copilot/report-templates': typeof AuthenticatedCopilotReportTemplatesRoute
  '/copilot/reports': typeof AuthenticatedCopilotReportsRoute
  '/infrastructure/audio': typeof AuthenticatedInfrastructureAudioRoute
  '/infrastructure/cameras': typeof AuthenticatedInfrastructureCamerasRoute
  '/infrastructure/engines': typeof AuthenticatedInfrastructureEnginesRoute
  '/infrastructure/gateways': typeof AuthenticatedInfrastructureGatewaysRoute
  '/infrastructure/health': typeof AuthenticatedInfrastructureHealthRoute
  '/infrastructure/network': typeof AuthenticatedInfrastructureNetworkRoute
  '/infrastructure/storage': typeof AuthenticatedInfrastructureStorageRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/administration': typeof AuthenticatedAdministrationIndexRoute
  '/conversationiq': typeof AuthenticatedConversationiqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/_authenticated/alert-analytics': typeof AuthenticatedAlertAnalyticsRoute
  '/_authenticated/alert-centre': typeof AuthenticatedAlertCentreRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/cameras': typeof AuthenticatedCamerasRoute
  '/_authenticated/command-centre': typeof AuthenticatedCommandCentreRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/filter-presets': typeof AuthenticatedFilterPresetsRoute
  '/_authenticated/live-monitor': typeof AuthenticatedLiveMonitorRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/outlets': typeof AuthenticatedOutletsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shared-preset': typeof AuthenticatedSharedPresetRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/copilot-audit': typeof AuthenticatedAdminCopilotAuditRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/administration/ai': typeof AuthenticatedAdministrationAiRoute
  '/_authenticated/administration/alerts': typeof AuthenticatedAdministrationAlertsRoute
  '/_authenticated/administration/api-keys': typeof AuthenticatedAdministrationApiKeysRoute
  '/_authenticated/administration/backup': typeof AuthenticatedAdministrationBackupRoute
  '/_authenticated/administration/general': typeof AuthenticatedAdministrationGeneralRoute
  '/_authenticated/administration/integrations': typeof AuthenticatedAdministrationIntegrationsRoute
  '/_authenticated/administration/keywords': typeof AuthenticatedAdministrationKeywordsRoute
  '/_authenticated/administration/languages': typeof AuthenticatedAdministrationLanguagesRoute
  '/_authenticated/administration/licensing': typeof AuthenticatedAdministrationLicensingRoute
  '/_authenticated/administration/quotas': typeof AuthenticatedAdministrationQuotasRoute
  '/_authenticated/administration/security': typeof AuthenticatedAdministrationSecurityRoute
  '/_authenticated/administration/speech': typeof AuthenticatedAdministrationSpeechRoute
  '/_authenticated/administration/usage': typeof AuthenticatedAdministrationUsageRoute
  '/_authenticated/conversationiq/$conversationId': typeof AuthenticatedConversationiqConversationIdRoute
  '/_authenticated/conversationiq/audit': typeof AuthenticatedConversationiqAuditRoute
  '/_authenticated/conversationiq/keywords': typeof AuthenticatedConversationiqKeywordsRoute
  '/_authenticated/conversationiq/languages': typeof AuthenticatedConversationiqLanguagesRoute
  '/_authenticated/conversationiq/queue': typeof AuthenticatedConversationiqQueueRoute
  '/_authenticated/conversationiq/redactions': typeof AuthenticatedConversationiqRedactionsRoute
  '/_authenticated/conversationiq/review': typeof AuthenticatedConversationiqReviewRoute
  '/_authenticated/conversationiq/search': typeof AuthenticatedConversationiqSearchRoute
  '/_authenticated/conversationiq/sla': typeof AuthenticatedConversationiqSlaRoute
  '/_authenticated/copilot/notifications': typeof AuthenticatedCopilotNotificationsRoute
  '/_authenticated/copilot/report-templates': typeof AuthenticatedCopilotReportTemplatesRoute
  '/_authenticated/copilot/reports': typeof AuthenticatedCopilotReportsRoute
  '/_authenticated/infrastructure/audio': typeof AuthenticatedInfrastructureAudioRoute
  '/_authenticated/infrastructure/cameras': typeof AuthenticatedInfrastructureCamerasRoute
  '/_authenticated/infrastructure/engines': typeof AuthenticatedInfrastructureEnginesRoute
  '/_authenticated/infrastructure/gateways': typeof AuthenticatedInfrastructureGatewaysRoute
  '/_authenticated/infrastructure/health': typeof AuthenticatedInfrastructureHealthRoute
  '/_authenticated/infrastructure/network': typeof AuthenticatedInfrastructureNetworkRoute
  '/_authenticated/infrastructure/storage': typeof AuthenticatedInfrastructureStorageRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/_authenticated/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/_authenticated/conversationiq/': typeof AuthenticatedConversationiqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/administration'
    | '/alert-analytics'
    | '/alert-centre'
    | '/alerts'
    | '/assistant'
    | '/audit-logs'
    | '/cameras'
    | '/command-centre'
    | '/conversations'
    | '/dashboard'
    | '/filter-presets'
    | '/live-monitor'
    | '/notifications'
    | '/outlets'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/shared-preset'
    | '/users'
    | '/admin/copilot-audit'
    | '/admin/roles'
    | '/administration/ai'
    | '/administration/alerts'
    | '/administration/api-keys'
    | '/administration/backup'
    | '/administration/general'
    | '/administration/integrations'
    | '/administration/keywords'
    | '/administration/languages'
    | '/administration/licensing'
    | '/administration/quotas'
    | '/administration/security'
    | '/administration/speech'
    | '/administration/usage'
    | '/conversationiq/$conversationId'
    | '/conversationiq/audit'
    | '/conversationiq/keywords'
    | '/conversationiq/languages'
    | '/conversationiq/queue'
    | '/conversationiq/redactions'
    | '/conversationiq/review'
    | '/conversationiq/search'
    | '/conversationiq/sla'
    | '/copilot/notifications'
    | '/copilot/report-templates'
    | '/copilot/reports'
    | '/infrastructure/audio'
    | '/infrastructure/cameras'
    | '/infrastructure/engines'
    | '/infrastructure/gateways'
    | '/infrastructure/health'
    | '/infrastructure/network'
    | '/infrastructure/storage'
    | '/api/public/telemetry'
    | '/administration/'
    | '/conversationiq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/alert-analytics'
    | '/alert-centre'
    | '/alerts'
    | '/assistant'
    | '/audit-logs'
    | '/cameras'
    | '/command-centre'
    | '/conversations'
    | '/dashboard'
    | '/filter-presets'
    | '/live-monitor'
    | '/notifications'
    | '/outlets'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/shared-preset'
    | '/users'
    | '/admin/copilot-audit'
    | '/admin/roles'
    | '/administration/ai'
    | '/administration/alerts'
    | '/administration/api-keys'
    | '/administration/backup'
    | '/administration/general'
    | '/administration/integrations'
    | '/administration/keywords'
    | '/administration/languages'
    | '/administration/licensing'
    | '/administration/quotas'
    | '/administration/security'
    | '/administration/speech'
    | '/administration/usage'
    | '/conversationiq/$conversationId'
    | '/conversationiq/audit'
    | '/conversationiq/keywords'
    | '/conversationiq/languages'
    | '/conversationiq/queue'
    | '/conversationiq/redactions'
    | '/conversationiq/review'
    | '/conversationiq/search'
    | '/conversationiq/sla'
    | '/copilot/notifications'
    | '/copilot/report-templates'
    | '/copilot/reports'
    | '/infrastructure/audio'
    | '/infrastructure/cameras'
    | '/infrastructure/engines'
    | '/infrastructure/gateways'
    | '/infrastructure/health'
    | '/infrastructure/network'
    | '/infrastructure/storage'
    | '/api/public/telemetry'
    | '/administration'
    | '/conversationiq'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/_authenticated/administration'
    | '/_authenticated/alert-analytics'
    | '/_authenticated/alert-centre'
    | '/_authenticated/alerts'
    | '/_authenticated/assistant'
    | '/_authenticated/audit-logs'
    | '/_authenticated/cameras'
    | '/_authenticated/command-centre'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/filter-presets'
    | '/_authenticated/live-monitor'
    | '/_authenticated/notifications'
    | '/_authenticated/outlets'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shared-preset'
    | '/_authenticated/users'
    | '/_authenticated/admin/copilot-audit'
    | '/_authenticated/admin/roles'
    | '/_authenticated/administration/ai'
    | '/_authenticated/administration/alerts'
    | '/_authenticated/administration/api-keys'
    | '/_authenticated/administration/backup'
    | '/_authenticated/administration/general'
    | '/_authenticated/administration/integrations'
    | '/_authenticated/administration/keywords'
    | '/_authenticated/administration/languages'
    | '/_authenticated/administration/licensing'
    | '/_authenticated/administration/quotas'
    | '/_authenticated/administration/security'
    | '/_authenticated/administration/speech'
    | '/_authenticated/administration/usage'
    | '/_authenticated/conversationiq/$conversationId'
    | '/_authenticated/conversationiq/audit'
    | '/_authenticated/conversationiq/keywords'
    | '/_authenticated/conversationiq/languages'
    | '/_authenticated/conversationiq/queue'
    | '/_authenticated/conversationiq/redactions'
    | '/_authenticated/conversationiq/review'
    | '/_authenticated/conversationiq/search'
    | '/_authenticated/conversationiq/sla'
    | '/_authenticated/copilot/notifications'
    | '/_authenticated/copilot/report-templates'
    | '/_authenticated/copilot/reports'
    | '/_authenticated/infrastructure/audio'
    | '/_authenticated/infrastructure/cameras'
    | '/_authenticated/infrastructure/engines'
    | '/_authenticated/infrastructure/gateways'
    | '/_authenticated/infrastructure/health'
    | '/_authenticated/infrastructure/network'
    | '/_authenticated/infrastructure/storage'
    | '/api/public/telemetry'
    | '/_authenticated/administration/'
    | '/_authenticated/conversationiq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared-preset': {
      id: '/_authenticated/shared-preset'
      path: '/shared-preset'
      fullPath: '/shared-preset'
      preLoaderRoute: typeof AuthenticatedSharedPresetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outlets': {
      id: '/_authenticated/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof AuthenticatedOutletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-monitor': {
      id: '/_authenticated/live-monitor'
      path: '/live-monitor'
      fullPath: '/live-monitor'
      preLoaderRoute: typeof AuthenticatedLiveMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filter-presets': {
      id: '/_authenticated/filter-presets'
      path: '/filter-presets'
      fullPath: '/filter-presets'
      preLoaderRoute: typeof AuthenticatedFilterPresetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-centre': {
      id: '/_authenticated/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof AuthenticatedCommandCentreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cameras': {
      id: '/_authenticated/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AuthenticatedCamerasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alert-centre': {
      id: '/_authenticated/alert-centre'
      path: '/alert-centre'
      fullPath: '/alert-centre'
      preLoaderRoute: typeof AuthenticatedAlertCentreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alert-analytics': {
      id: '/_authenticated/alert-analytics'
      path: '/alert-analytics'
      fullPath: '/alert-analytics'
      preLoaderRoute: typeof AuthenticatedAlertAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/': {
      id: '/_authenticated/conversationiq/'
      path: '/conversationiq'
      fullPath: '/conversationiq/'
      preLoaderRoute: typeof AuthenticatedConversationiqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration/': {
      id: '/_authenticated/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthenticatedAdministrationIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/infrastructure/storage': {
      id: '/_authenticated/infrastructure/storage'
      path: '/infrastructure/storage'
      fullPath: '/infrastructure/storage'
      preLoaderRoute: typeof AuthenticatedInfrastructureStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/network': {
      id: '/_authenticated/infrastructure/network'
      path: '/infrastructure/network'
      fullPath: '/infrastructure/network'
      preLoaderRoute: typeof AuthenticatedInfrastructureNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/health': {
      id: '/_authenticated/infrastructure/health'
      path: '/infrastructure/health'
      fullPath: '/infrastructure/health'
      preLoaderRoute: typeof AuthenticatedInfrastructureHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/gateways': {
      id: '/_authenticated/infrastructure/gateways'
      path: '/infrastructure/gateways'
      fullPath: '/infrastructure/gateways'
      preLoaderRoute: typeof AuthenticatedInfrastructureGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/engines': {
      id: '/_authenticated/infrastructure/engines'
      path: '/infrastructure/engines'
      fullPath: '/infrastructure/engines'
      preLoaderRoute: typeof AuthenticatedInfrastructureEnginesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/cameras': {
      id: '/_authenticated/infrastructure/cameras'
      path: '/infrastructure/cameras'
      fullPath: '/infrastructure/cameras'
      preLoaderRoute: typeof AuthenticatedInfrastructureCamerasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure/audio': {
      id: '/_authenticated/infrastructure/audio'
      path: '/infrastructure/audio'
      fullPath: '/infrastructure/audio'
      preLoaderRoute: typeof AuthenticatedInfrastructureAudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/reports': {
      id: '/_authenticated/copilot/reports'
      path: '/copilot/reports'
      fullPath: '/copilot/reports'
      preLoaderRoute: typeof AuthenticatedCopilotReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/report-templates': {
      id: '/_authenticated/copilot/report-templates'
      path: '/copilot/report-templates'
      fullPath: '/copilot/report-templates'
      preLoaderRoute: typeof AuthenticatedCopilotReportTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/notifications': {
      id: '/_authenticated/copilot/notifications'
      path: '/copilot/notifications'
      fullPath: '/copilot/notifications'
      preLoaderRoute: typeof AuthenticatedCopilotNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/sla': {
      id: '/_authenticated/conversationiq/sla'
      path: '/conversationiq/sla'
      fullPath: '/conversationiq/sla'
      preLoaderRoute: typeof AuthenticatedConversationiqSlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/search': {
      id: '/_authenticated/conversationiq/search'
      path: '/conversationiq/search'
      fullPath: '/conversationiq/search'
      preLoaderRoute: typeof AuthenticatedConversationiqSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/review': {
      id: '/_authenticated/conversationiq/review'
      path: '/conversationiq/review'
      fullPath: '/conversationiq/review'
      preLoaderRoute: typeof AuthenticatedConversationiqReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/redactions': {
      id: '/_authenticated/conversationiq/redactions'
      path: '/conversationiq/redactions'
      fullPath: '/conversationiq/redactions'
      preLoaderRoute: typeof AuthenticatedConversationiqRedactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/queue': {
      id: '/_authenticated/conversationiq/queue'
      path: '/conversationiq/queue'
      fullPath: '/conversationiq/queue'
      preLoaderRoute: typeof AuthenticatedConversationiqQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/languages': {
      id: '/_authenticated/conversationiq/languages'
      path: '/conversationiq/languages'
      fullPath: '/conversationiq/languages'
      preLoaderRoute: typeof AuthenticatedConversationiqLanguagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/keywords': {
      id: '/_authenticated/conversationiq/keywords'
      path: '/conversationiq/keywords'
      fullPath: '/conversationiq/keywords'
      preLoaderRoute: typeof AuthenticatedConversationiqKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/audit': {
      id: '/_authenticated/conversationiq/audit'
      path: '/conversationiq/audit'
      fullPath: '/conversationiq/audit'
      preLoaderRoute: typeof AuthenticatedConversationiqAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversationiq/$conversationId': {
      id: '/_authenticated/conversationiq/$conversationId'
      path: '/conversationiq/$conversationId'
      fullPath: '/conversationiq/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationiqConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration/usage': {
      id: '/_authenticated/administration/usage'
      path: '/usage'
      fullPath: '/administration/usage'
      preLoaderRoute: typeof AuthenticatedAdministrationUsageRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/speech': {
      id: '/_authenticated/administration/speech'
      path: '/speech'
      fullPath: '/administration/speech'
      preLoaderRoute: typeof AuthenticatedAdministrationSpeechRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/security': {
      id: '/_authenticated/administration/security'
      path: '/security'
      fullPath: '/administration/security'
      preLoaderRoute: typeof AuthenticatedAdministrationSecurityRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/quotas': {
      id: '/_authenticated/administration/quotas'
      path: '/quotas'
      fullPath: '/administration/quotas'
      preLoaderRoute: typeof AuthenticatedAdministrationQuotasRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/licensing': {
      id: '/_authenticated/administration/licensing'
      path: '/licensing'
      fullPath: '/administration/licensing'
      preLoaderRoute: typeof AuthenticatedAdministrationLicensingRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/languages': {
      id: '/_authenticated/administration/languages'
      path: '/languages'
      fullPath: '/administration/languages'
      preLoaderRoute: typeof AuthenticatedAdministrationLanguagesRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/keywords': {
      id: '/_authenticated/administration/keywords'
      path: '/keywords'
      fullPath: '/administration/keywords'
      preLoaderRoute: typeof AuthenticatedAdministrationKeywordsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/integrations': {
      id: '/_authenticated/administration/integrations'
      path: '/integrations'
      fullPath: '/administration/integrations'
      preLoaderRoute: typeof AuthenticatedAdministrationIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/general': {
      id: '/_authenticated/administration/general'
      path: '/general'
      fullPath: '/administration/general'
      preLoaderRoute: typeof AuthenticatedAdministrationGeneralRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/backup': {
      id: '/_authenticated/administration/backup'
      path: '/backup'
      fullPath: '/administration/backup'
      preLoaderRoute: typeof AuthenticatedAdministrationBackupRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/api-keys': {
      id: '/_authenticated/administration/api-keys'
      path: '/api-keys'
      fullPath: '/administration/api-keys'
      preLoaderRoute: typeof AuthenticatedAdministrationApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/alerts': {
      id: '/_authenticated/administration/alerts'
      path: '/alerts'
      fullPath: '/administration/alerts'
      preLoaderRoute: typeof AuthenticatedAdministrationAlertsRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/administration/ai': {
      id: '/_authenticated/administration/ai'
      path: '/ai'
      fullPath: '/administration/ai'
      preLoaderRoute: typeof AuthenticatedAdministrationAiRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/copilot-audit': {
      id: '/_authenticated/admin/copilot-audit'
      path: '/admin/copilot-audit'
      fullPath: '/admin/copilot-audit'
      preLoaderRoute: typeof AuthenticatedAdminCopilotAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdministrationRouteChildren {
  AuthenticatedAdministrationAiRoute: typeof AuthenticatedAdministrationAiRoute
  AuthenticatedAdministrationAlertsRoute: typeof AuthenticatedAdministrationAlertsRoute
  AuthenticatedAdministrationApiKeysRoute: typeof AuthenticatedAdministrationApiKeysRoute
  AuthenticatedAdministrationBackupRoute: typeof AuthenticatedAdministrationBackupRoute
  AuthenticatedAdministrationGeneralRoute: typeof AuthenticatedAdministrationGeneralRoute
  AuthenticatedAdministrationIntegrationsRoute: typeof AuthenticatedAdministrationIntegrationsRoute
  AuthenticatedAdministrationKeywordsRoute: typeof AuthenticatedAdministrationKeywordsRoute
  AuthenticatedAdministrationLanguagesRoute: typeof AuthenticatedAdministrationLanguagesRoute
  AuthenticatedAdministrationLicensingRoute: typeof AuthenticatedAdministrationLicensingRoute
  AuthenticatedAdministrationQuotasRoute: typeof AuthenticatedAdministrationQuotasRoute
  AuthenticatedAdministrationSecurityRoute: typeof AuthenticatedAdministrationSecurityRoute
  AuthenticatedAdministrationSpeechRoute: typeof AuthenticatedAdministrationSpeechRoute
  AuthenticatedAdministrationUsageRoute: typeof AuthenticatedAdministrationUsageRoute
  AuthenticatedAdministrationIndexRoute: typeof AuthenticatedAdministrationIndexRoute
}

const AuthenticatedAdministrationRouteChildren: AuthenticatedAdministrationRouteChildren =
  {
    AuthenticatedAdministrationAiRoute: AuthenticatedAdministrationAiRoute,
    AuthenticatedAdministrationAlertsRoute:
      AuthenticatedAdministrationAlertsRoute,
    AuthenticatedAdministrationApiKeysRoute:
      AuthenticatedAdministrationApiKeysRoute,
    AuthenticatedAdministrationBackupRoute:
      AuthenticatedAdministrationBackupRoute,
    AuthenticatedAdministrationGeneralRoute:
      AuthenticatedAdministrationGeneralRoute,
    AuthenticatedAdministrationIntegrationsRoute:
      AuthenticatedAdministrationIntegrationsRoute,
    AuthenticatedAdministrationKeywordsRoute:
      AuthenticatedAdministrationKeywordsRoute,
    AuthenticatedAdministrationLanguagesRoute:
      AuthenticatedAdministrationLanguagesRoute,
    AuthenticatedAdministrationLicensingRoute:
      AuthenticatedAdministrationLicensingRoute,
    AuthenticatedAdministrationQuotasRoute:
      AuthenticatedAdministrationQuotasRoute,
    AuthenticatedAdministrationSecurityRoute:
      AuthenticatedAdministrationSecurityRoute,
    AuthenticatedAdministrationSpeechRoute:
      AuthenticatedAdministrationSpeechRoute,
    AuthenticatedAdministrationUsageRoute:
      AuthenticatedAdministrationUsageRoute,
    AuthenticatedAdministrationIndexRoute:
      AuthenticatedAdministrationIndexRoute,
  }

const AuthenticatedAdministrationRouteWithChildren =
  AuthenticatedAdministrationRoute._addFileChildren(
    AuthenticatedAdministrationRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRouteWithChildren
  AuthenticatedAlertAnalyticsRoute: typeof AuthenticatedAlertAnalyticsRoute
  AuthenticatedAlertCentreRoute: typeof AuthenticatedAlertCentreRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedCamerasRoute: typeof AuthenticatedCamerasRoute
  AuthenticatedCommandCentreRoute: typeof AuthenticatedCommandCentreRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilterPresetsRoute: typeof AuthenticatedFilterPresetsRoute
  AuthenticatedLiveMonitorRoute: typeof AuthenticatedLiveMonitorRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOutletsRoute: typeof AuthenticatedOutletsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSharedPresetRoute: typeof AuthenticatedSharedPresetRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminCopilotAuditRoute: typeof AuthenticatedAdminCopilotAuditRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedConversationiqConversationIdRoute: typeof AuthenticatedConversationiqConversationIdRoute
  AuthenticatedConversationiqAuditRoute: typeof AuthenticatedConversationiqAuditRoute
  AuthenticatedConversationiqKeywordsRoute: typeof AuthenticatedConversationiqKeywordsRoute
  AuthenticatedConversationiqLanguagesRoute: typeof AuthenticatedConversationiqLanguagesRoute
  AuthenticatedConversationiqQueueRoute: typeof AuthenticatedConversationiqQueueRoute
  AuthenticatedConversationiqRedactionsRoute: typeof AuthenticatedConversationiqRedactionsRoute
  AuthenticatedConversationiqReviewRoute: typeof AuthenticatedConversationiqReviewRoute
  AuthenticatedConversationiqSearchRoute: typeof AuthenticatedConversationiqSearchRoute
  AuthenticatedConversationiqSlaRoute: typeof AuthenticatedConversationiqSlaRoute
  AuthenticatedCopilotNotificationsRoute: typeof AuthenticatedCopilotNotificationsRoute
  AuthenticatedCopilotReportTemplatesRoute: typeof AuthenticatedCopilotReportTemplatesRoute
  AuthenticatedCopilotReportsRoute: typeof AuthenticatedCopilotReportsRoute
  AuthenticatedInfrastructureAudioRoute: typeof AuthenticatedInfrastructureAudioRoute
  AuthenticatedInfrastructureCamerasRoute: typeof AuthenticatedInfrastructureCamerasRoute
  AuthenticatedInfrastructureEnginesRoute: typeof AuthenticatedInfrastructureEnginesRoute
  AuthenticatedInfrastructureGatewaysRoute: typeof AuthenticatedInfrastructureGatewaysRoute
  AuthenticatedInfrastructureHealthRoute: typeof AuthenticatedInfrastructureHealthRoute
  AuthenticatedInfrastructureNetworkRoute: typeof AuthenticatedInfrastructureNetworkRoute
  AuthenticatedInfrastructureStorageRoute: typeof AuthenticatedInfrastructureStorageRoute
  AuthenticatedConversationiqIndexRoute: typeof AuthenticatedConversationiqIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrationRoute:
    AuthenticatedAdministrationRouteWithChildren,
  AuthenticatedAlertAnalyticsRoute: AuthenticatedAlertAnalyticsRoute,
  AuthenticatedAlertCentreRoute: AuthenticatedAlertCentreRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedCamerasRoute: AuthenticatedCamerasRoute,
  AuthenticatedCommandCentreRoute: AuthenticatedCommandCentreRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilterPresetsRoute: AuthenticatedFilterPresetsRoute,
  AuthenticatedLiveMonitorRoute: AuthenticatedLiveMonitorRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOutletsRoute: AuthenticatedOutletsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSharedPresetRoute: AuthenticatedSharedPresetRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminCopilotAuditRoute: AuthenticatedAdminCopilotAuditRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedConversationiqConversationIdRoute:
    AuthenticatedConversationiqConversationIdRoute,
  AuthenticatedConversationiqAuditRoute: AuthenticatedConversationiqAuditRoute,
  AuthenticatedConversationiqKeywordsRoute:
    AuthenticatedConversationiqKeywordsRoute,
  AuthenticatedConversationiqLanguagesRoute:
    AuthenticatedConversationiqLanguagesRoute,
  AuthenticatedConversationiqQueueRoute: AuthenticatedConversationiqQueueRoute,
  AuthenticatedConversationiqRedactionsRoute:
    AuthenticatedConversationiqRedactionsRoute,
  AuthenticatedConversationiqReviewRoute:
    AuthenticatedConversationiqReviewRoute,
  AuthenticatedConversationiqSearchRoute:
    AuthenticatedConversationiqSearchRoute,
  AuthenticatedConversationiqSlaRoute: AuthenticatedConversationiqSlaRoute,
  AuthenticatedCopilotNotificationsRoute:
    AuthenticatedCopilotNotificationsRoute,
  AuthenticatedCopilotReportTemplatesRoute:
    AuthenticatedCopilotReportTemplatesRoute,
  AuthenticatedCopilotReportsRoute: AuthenticatedCopilotReportsRoute,
  AuthenticatedInfrastructureAudioRoute: AuthenticatedInfrastructureAudioRoute,
  AuthenticatedInfrastructureCamerasRoute:
    AuthenticatedInfrastructureCamerasRoute,
  AuthenticatedInfrastructureEnginesRoute:
    AuthenticatedInfrastructureEnginesRoute,
  AuthenticatedInfrastructureGatewaysRoute:
    AuthenticatedInfrastructureGatewaysRoute,
  AuthenticatedInfrastructureHealthRoute:
    AuthenticatedInfrastructureHealthRoute,
  AuthenticatedInfrastructureNetworkRoute:
    AuthenticatedInfrastructureNetworkRoute,
  AuthenticatedInfrastructureStorageRoute:
    AuthenticatedInfrastructureStorageRoute,
  AuthenticatedConversationiqIndexRoute: AuthenticatedConversationiqIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
